version: '2'

services:
    web1:
        environment:
            - postgres_host=postgres1
        restart: always
        build: ./blockchain_core
        ports:
            - "5000"
        command: python flask_app.py
        depends_on:
            - postgres1

    postgres1:
        restart: always
        build: ./postgres
        volumes_from:
            - data1
        ports:
            - "5432"

    data1:
        image: postgres:9.6
        volumes:
            - /var/lib/postgresql
        command: "true"

    web2:
        environment:
            - postgres_host=postgres2
        restart: always
        build: ./blockchain_core
        ports:
            - "5000"
        command: python flask_app.py
        depends_on:
            - postgres2

    postgres2:
        restart: always
        build: ./postgres
        volumes_from:
            - data2
        ports:
            - "5432"

    data2:
        image: postgres:9.6
        volumes:
            - /var/lib/postgresql
        command: "true"
