version: '2'

networks:
   testchain_net:
       ipam:
           driver: default
           config:
               - subnet: 172.32.0.0/16

services:
   postgres:
       restart: always
       build: ./postgres
       networks:
           testchain_net:
               ipv4_address: 172.32.0.2
       ports:
           - "5432"
       depends_on:
           - data

   data:
       image: postgres:9.6
       networks:
           testchain_net:
               ipv4_address: 172.32.0.3
       volumes:
           - /var/lib/postgresql
       command: "true"

   web1:
       environment:
           - db_suffix=web1
#           - postgres_host=postgres
       restart: always
       build: ./blockchain_core
       ports:
           - "5000"
       command: python flask_app.py
       networks:
           testchain_net:
               ipv4_address: 172.32.0.4
       depends_on:
           - postgres


   web2:
       environment:
           - db_suffix=web2
#           - postgres_host=postgres
       restart: always
       build: ./blockchain_core
       ports:
           - "5000"
       command: python flask_app.py
       networks:
           testchain_net:
               ipv4_address: 172.32.0.5
       depends_on:
           - postgres


   web3:
       environment:
           - db_suffix=web3
#           - postgres_host=postgres
       restart: always
       build: ./blockchain_core
       ports:
           - "5000"
       command: python flask_app.py
       networks:
           testchain_net:
               ipv4_address: 172.32.0.6
       depends_on:
           - postgres

