node_range = 10
f = open('test.yml', 'w')

f.write("version: '2'\n")
f.write("\n")
f.write("networks:\n")
f.write("   testchain_net:\n")
f.write("       ipam:\n")
f.write("           driver: default\n")
f.write("           config:\n")
f.write("               - subnet: 172.32.0.0/16\n")
f.write("\n")
f.write("services:\n")
for iter in range(1,node_range+1):
    f.write("\n")
    f.write("   web"+str(iter)+":\n")
    f.write("       environment:\n")
    f.write("           - postgres_host=postgres"+str(iter)+"\n")
    f.write("       restart: always\n")
    f.write("       build: ./blockchain_core\n")
    f.write("       ports:\n")
    f.write("           - \"5000\"\n")
    f.write("       command: python flask_app.py\n")
    f.write("       networks:\n")
    f.write("           testchain_net:\n")
    f.write("               ipv4_address: 172.32.0."+str(3*iter-1)+"\n")
    f.write("       depends_on:\n")
    f.write("           - postgres"+str(iter)+"\n")
    f.write("\n")
    f.write("   postgres"+str(iter)+":\n")
    f.write("       restart: always\n")
    f.write("       build: ./postgres\n")
    f.write("       networks:\n")
    f.write("           testchain_net:\n")
    f.write("               ipv4_address: 172.32.0."+str(3*iter)+"\n")
    f.write("       ports:\n")
    f.write("           - \"5432\"\n")
    f.write("       depends_on:\n")
    f.write("           - data"+str(iter)+"\n")
    f.write("\n")
    f.write("   data"+str(iter)+":\n")
    f.write("       image: postgres:9.6\n")
    f.write("       networks:\n")
    f.write("           testchain_net:\n")
    f.write("               ipv4_address: 172.32.0."+str(3*iter+1)+"\n")
    f.write("       volumes:\n")
    f.write("           - /var/lib/postgresql\n")
    f.write("       command: \"true\"\n")

f.close()
