version: '2'

services:
    web:
        restart: always
        build: ./web
        ports:
            - "8000:8000"
        command: python flask_app.py
        depends_on:
            - postgres

    postgres:
        restart: always
        build: ./db
        volumes_from:
            - data
        ports:
            - "5433:5432"

    data:
        image: postgres:9.6
        volumes:
            - /var/lib/postgresql
        command: "true"
